// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvqvayyjukiqaeyjadtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cXZheXlqdWtpcWFleWphZHR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODI1MDgsImV4cCI6MjA2Njg1ODUwOH0.I2k8Y3W-iZWDwenhXYLGMhNoJ89vSyoI16wrgEP63_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});